### ISSUE TITLE
Get retryDelta without "using" the ratelimiter

### ISSUE THREAD

**Issue by MicMonen** [BitMEX/node-redis-token-bucket-ratelimiter#6]
Is there a way to get the retryDelta without "using" the ratelimiter?

When you use amount = 0 you will get the amount of token left which is nice but getting the correct retryDelta is what I want.

Anyway the package is a nice implementation of the concept.

**Comment by STRML** [comment]
`retryDelta` is very simple math. https://github.com/BitMEX/node-redis-token-bucket-ratelimiter/blob/6053e241b44c98a9361ab96bf02df09e772ae631/lua/rollingLimit.lua#L64

I'm not sure I understand the use case - you have somebody you know has breached their limit, but you don't want to use or store the `retryDelta` returned when they breached it?

**Comment by MicMonen** [comment]
My use case is that a user is allowed 1 action every 5 minutes. I want an UI with a countdown based on the retryDelta if the user is not allowed to perform the action yet, else I show a button.

There is currently no way to get the current retryDelta without actually using the rate limiter (which subsequent lock themself out again), I only can the remaining count when using limiter.use(key, 0).

**Comment by MicMonen** [comment]
I was wondering if it was able to have to functionality without another datastore. Like to get the id status or to simulate without actually perform the Redis-queries. But I can store the retryDelta separately like you suggested, so nvm this issue.
